# Generated by Django 2.1.7 on 2019-05-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('cod_blog', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('imagen', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
