# Generated by Django 2.1.7 on 2019-06-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='destinatarios',
            field=models.IntegerField(default=25),
        ),
    ]
