# Generated by Django 2.1.7 on 2019-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_auto_20190604_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='destinatarios',
            field=models.IntegerField(),
        ),
    ]
