# Generated by Django 2.1.7 on 2019-06-06 20:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_auto_20190605_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
