# Generated by Django 2.1.7 on 2019-06-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_auto_20190606_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='descripcion',
            field=models.CharField(max_length=12),
        ),
    ]
