# Generated by Django 2.1.7 on 2019-05-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portada',
            name='id',
        ),
        migrations.AddField(
            model_name='portada',
            name='cod_portada',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='portada',
            table='portada',
        ),
    ]
