# Generated by Django 2.1.7 on 2019-06-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0003_auto_20190531_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='portada',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
