# Generated by Django 2.1.7 on 2019-06-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('cod_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.SmallIntegerField(blank=True, null=True)),
                ('talla', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen_url', models.ImageField(upload_to='projects')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prendas',
                'db_table': 'prenda',
            },
        ),
    ]
