# Generated by Django 2.1.7 on 2019-05-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('cod_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.SmallIntegerField(blank=True, null=True)),
                ('talla', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('imagen', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prenda',
            },
        ),
    ]
