# Generated by Django 2.1.7 on 2019-05-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190517_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prenda',
        ),
    ]
