# Generated by Django 2.1.7 on 2019-06-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_delete_prenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('cod_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('correo', models.CharField(max_length=200)),
                ('telefono', models.BigIntegerField()),
                ('asunto', models.TextField()),
            ],
            options={
                'db_table': 'mensajes',
            },
        ),
    ]
