# Generated by Django 2.1.7 on 2019-06-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190531_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajes',
            options={'ordering': ['-fecha_recibido'], 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.RenameField(
            model_name='mensajes',
            old_name='fecha_creacion',
            new_name='fecha_recibido',
        ),
    ]
