# Generated by Django 2.1.7 on 2019-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190601_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='telefono',
            field=models.TextField(),
        ),
    ]
