# Generated by Django 2.1.7 on 2019-06-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_subscriptores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptores',
            options={'ordering': ['-fecha_subscripcion'], 'verbose_name_plural': 'Subscriptores'},
        ),
    ]
